packages:
  - browser
  - website

allowedDeprecatedVersions:
  whatwg-encoding: '*'

catalog:
  '@fortawesome/fontawesome-svg-core': ^7.2.0
  '@fortawesome/free-solid-svg-icons': ^7.2.0
  '@fortawesome/react-fontawesome': ^3.2.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.2
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
