packages:
  - 'browser'
  - 'website'

catalog:
  "@fortawesome/fontawesome-svg-core": "^7.1.0"
  "@fortawesome/free-solid-svg-icons": "^7.1.0"
  "@fortawesome/react-fontawesome": "^3.1.1"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "eslint": "^9.39.1"
  "react": "^19.2.1"
  "react-dom": "^19.2.1"
  "typescript": "^5.9.3"
